### ISSUE TITLE
Nothing happen clicking on "Initial Setup"

### ISSUE THREAD

**Issue by jeanguerin** [awslabs/aws-for-wordpress#32]
Hello, 

I have installed the plugin on WordPress 5.3.1 with Divi Theme.
The website is hosted on an EC2 instance with a role attached, belonging to a target group of an ELB. 

I would like use aws for wordpress plugin to deploy on Cloudfront.
In General tab, I let the fields empty. In the Cloudfront tab, Origin Domain Name is filled with the ELB address, and the CloudFront Alternate Domain Name with our domain (www.example.com).

When I click on "Initial Setup" nothing happen.
In the browser console, I found this error, coming from AJAX.
```
load-scripts.php?c=0&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.3.1:8 JQMIGRATE: Migrate is installed, version 1.4.1
/wp-admin/admin-ajax.php?_fs_blog_admin=true:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
VM134:1 POST http://ec2-34-255-209-250.eu-west-1.compute.amazonaws.com/wp-admin/admin-ajax.php?_fs_blog_admin=true 500 (Internal Server Error)
(anonymous) @ VM134:1
send @ load-scripts.php?c=0&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.3.1:4
ajax @ load-scripts.php?c=0&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.3.1:4
begin_cloudformation @ amazon_cf.js:120
(anonymous) @ amazon_cf.js:49
dispatch @ load-scripts.php?c=0&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.3.1:3
r.handle @ load-scripts.php?c=0&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.3.1:3
```

Could you please help me ?

Best,
JG

**Comment by joshbean** [comment]
Hi JG,

Sorry for the long delay in responding! This might be an issue with your theme. Can you try deactivating your theme, then setting up the AWS for WordPress plugin, then reactivating your theme? If that doesn't work, let us know and we'll try to help as best we can.

Josh

**Comment by jeanguerin** [comment]
Hello,

I have solved my issue.
The issue came from the lack of "php-xml" package in my ec2 instance.
This display an error in General tab but not in Cloud front tab of the plugin.

Best,

Jean

**Comment by joshbean** [comment]
Great! I'm glad you got your issue solved. And thanks for letting us know the solution. I'll look for a place to mention that in the documentation, so that it doesn't trip up others.
